prompt0 = "A cat holding a sign that says Tan Ngo"
prompt1 = "A high-quality image of a leopard gecko that’s all yellow with no black on his yellow skin. His eyes are black and super high-quality IMAX movie style. He has a moist look and has a lot of depth. His pink lounge slightly out licking a yellow banana popsicle."
prompt2 = "1boy solo, mature man, Jang Ho-joong, shirtless, muscular, hairy chest, shorts, stubble, facial hair, black hair, looking at you, standing, veiny arms, messy hair, black eyes, serious expression, front view, realistic, blake alexander style, best quality, best aesthetic, high details"
prompt3 = "A woman seated on a sofa, facing the camera directly, with blonde hair pulled back and a few loose strands. She wears a black deep V-neck dress and a statement necklace. Her hands rest lightly on her lap. The background features large windows with soft, natural light illuminating her face."
prompt4 = "High image quality, high color saturation Milan fashion show, runway Beautiful Japanese female model wearing the sample morning dress This (beautiful and cute) Japanese female model has big eyes, a high nose, is tall and has long limbs, and the figure of a fashion model The sample morning dresses come in a variety of patterns, including (Japanese cherry blossom pattern)."
prompt5 = "Ultra-realistic close-up of a tiny baby pig, smaller than a fingernail, sitting on the tip of a person’s finger. The baby pig has soft pink skin with delicate wrinkles, tiny ears, and a cute, upturned snout. Its little hooves rest gently on the fingertip, and the close-up emphasizes the fine details of its skin texture, snout, and hooves, capturing its adorable yet surprisingly strong look. Soft lighting should highlight the contrast between the piglet's miniature size and the human finger, enhancing the charm and detail of the tiny animal."
prompt6 = "An image of a woman with a hyperrealistic style, showcasing an elaborate body paint design. The skin should be painted in segments of black, gold, and black, with patterns that mimic flowing lines and dots. The face features an asymmetrical mask-like effect, with one eye highlighted in gold and the other in black, complemented by matching eyeshadow. The lips are a vibrant red, contrasting with the face paint. The figure's blonde hair is tousled, enhancing the fantastical element. The image should blend the precision of hyperrealism with the creativity of fantasy body art."
prompt7 = "A sleek, photorealistic depiction of a stunning redhead, her vibrant green eyes locked onto the viewer as she confidently poses in a futuristic space station setting. She's clad in a form-fitting Jedi-inspired suit with a flowing hood, showcasing her impressive assets: massive breasts, thick lips, and tantalizing cleavage that threatens to spill over her outfit. Her slender physique is accentuated by the wide crotch of the suit, drawing attention to her toned physique. Makeup is applied sparingly, allowing her natural beauty to shine through as she gazes directly at the viewer with an air of quiet confidence."
prompt8 = "Create a professional, ultra-realistic 4K image of a high-tech mega drone capturing an aerial view of a futuristic city at night. The drone hovers high above, equipped with advanced cameras and sensors, offering us a breathtaking perspective of the city below. The urban landscape is illuminated by vibrant and warm neon lights from towering skyscrapers, with intricate details on the buildings’ facades and the bustling streets far below. The colors are hyper-vivid and warm, enhancing the dynamic atmosphere of the city at night. The drone’s sleek, cutting-edge design is visible in the foreground, showcasing the blend of technology and urban life in a stunning visual display."
prompt9 = "A young woman with long dark hair stands in a snowy forest, her seductive smile illuminated by soft, warm lighting. She wears a white fur coat with a large hood, draped over her shoulders, and a black lingerie set with thigh-high stockings. One hand rests on her hip, the other on her thigh, as she poses confidently. Snowflakes gently fall, creating a dreamy, ethereal atmosphere. The scene is framed with a shallow depth of field, emphasizing her expression and the intricate details of her attire. The lighting is moody and atmospheric, with a soft, diffused key light from the front and a subtle rim light from behind, casting a gentle glow on her skin. The background trees are covered in snow, adding to the serene, otherworldly mood. "

list_prompts_old = [prompt0, prompt1, prompt2, prompt3, prompt4, prompt5, prompt6, prompt7, prompt8, prompt9]
# easy
p0 = "A serene forest clearing with soft sunlight filtering through tall pine trees and a gentle stream running through."
p1 = "A futuristic city skyline at dusk, glowing neon signs and flying cars creating a vibrant and dynamic atmosphere."
p2 = "A mystical underwater kingdom with glowing coral reefs, ancient ruins, and colorful marine life swimming in harmony."
p3 = "A cozy library filled with towering wooden shelves, warm golden light, and an inviting armchair near a crackling fireplace."
p4 = "A dramatic mountain peak surrounded by swirling mist, with a lone adventurer standing at the summit gazing into the horizon."
p5 = "A tranquil Japanese garden with a red torii gate, koi pond, and blossoming cherry trees under a bright blue sky."
p6 = "A bustling medieval marketplace filled with colorful stalls, lively merchants, and townsfolk in traditional clothing."
p7 = "A magical forest glowing with bioluminescent plants and mythical creatures wandering between the trees in the moonlight."
p8 = "An abandoned spaceship interior with flickering lights, broken panels, and a sense of eerie stillness."
p9 = "A futuristic lab with sleek white surfaces, holographic interfaces, and scientists working on advanced robotic technology."
p10 = "A steampunk airship flying above a sprawling city, its intricate gears and propellers gleaming in the golden sunset."
p11 = "A mysterious cave illuminated by crystals, with an underground waterfall cascading into a shimmering pool below."
p12 = "A desert landscape at sunset with towering sand dunes, a lone traveler riding a camel, and a distant oasis."
p13 = "A vibrant carnival at night with colorful lights, a Ferris wheel, and excited crowds enjoying the festive atmosphere."
p14 = "A serene beach at dawn with soft waves, seashells scattered on the sand, and a pastel-hued sky."
p15 = "A futuristic cyberpunk street scene filled with towering holograms, bustling crowds, and vibrant neon lights reflecting on wet pavement."
p16 = "A peaceful winter village covered in snow, with glowing lanterns and smoke rising from cozy chimneys."
p17 = "An ancient castle perched on a cliffside, with storm clouds gathering above and waves crashing below."
p18 = "A fantasy tavern bustling with adventurers, wooden tables laden with food, and a bard singing by the hearth."
p19 = "A surreal dreamscape with floating islands, cascading waterfalls in the sky, and a vivid rainbow arching across the horizon."
# medium
p20 = "An enchanted forest where the trees glow with soft hues of blue and green, magical creatures dart between the foliage, and a hidden waterfall sparkles under moonlight."
p21 = "A grand futuristic city with sleek glass towers, flying vehicles zipping between buildings, and a central park filled with lush greenery and winding pathways."
p22 = "An ancient desert temple partially buried in golden sand, its weathered stone carvings depicting long-lost civilizations illuminated by the setting sun."
p23 = "A tranquil mountain lake surrounded by towering pine trees, its surface reflecting the fiery colors of a sunset while a lone canoe drifts quietly."
p24 = "A cyberpunk market bustling with energy, filled with neon lights, diverse vendors offering exotic goods, and shadowy figures navigating the narrow alleyways."
p25 = "A majestic dragon perched atop a jagged cliff, its scales glistening in the sunlight, with vast plains stretching endlessly below."
p26 = "A whimsical tea party in a meadow filled with oversized mushrooms, floating teacups, and fantastical creatures engaged in lively conversation."
p27 = "A sprawling medieval castle surrounded by lush green fields, its towering spires reaching into a cloudy sky, and a drawbridge spanning a sparkling moat."
p28 = "A serene tropical beach at twilight, the horizon painted with vivid purples and oranges, as gentle waves lap against the shore where lanterns are softly glowing."
p29 = "An alien world with a vibrant, otherworldly landscape featuring towering crystalline structures, purple skies, and bioluminescent plants lighting the ground."
p30 = "A peaceful village square during a summer festival, colorful banners and lanterns strung across cobblestone streets, with cheerful townsfolk enjoying music and dancing."
p31 = "A fantastical treehouse built within a massive ancient tree, with glowing windows, winding staircases, and hanging bridges connecting different levels."
p32 = "A futuristic laboratory filled with sleek holographic displays, advanced robots working alongside humans, and a sense of groundbreaking discovery in the air."
p33 = "A surreal underwater landscape featuring a sunken pirate ship, glowing jellyfish drifting among the ruins, and shimmering schools of fish weaving in and out of coral."
p34 = "A dramatic battlefield with medieval knights clashing under stormy skies, banners flying high, and the glow of torches illuminating the chaos."
p35 = "A bustling space station orbiting a distant planet, with massive observation windows showcasing a galaxy of stars and ships docking and departing in harmony."
p36 = "A hauntingly beautiful abandoned mansion overtaken by nature, its grand staircase covered in vines, and rays of light piercing through shattered windows."
p37 = "An icy arctic landscape with a shimmering aurora borealis overhead, a team of explorers trekking across the snow, and a polar bear observing from a distance."
p38 = "A vibrant fantasy city built into a mountainside, its cascading waterfalls powering glowing crystal lights, and airships flying gracefully above."
p39 = "A peaceful zen garden at sunrise, with meticulously raked gravel, a small stone bridge over a koi pond, and a bamboo fountain gently trickling water."
p40 = "A dystopian city where towering skyscrapers loom over crumbling streets, neon graffiti covers walls, and a lone figure in a hooded cloak navigates the shadows."
p41 = "A steampunk workshop filled with intricate gears and tools, blueprints scattered across a wooden table, and a half-finished mechanical invention glowing faintly."
p42 = "A mysterious jungle temple hidden within dense foliage, with glowing runes on its ancient stone walls and a sense of untold secrets waiting to be discovered."
p43 = "A serene countryside at dawn, with golden sunlight illuminating rolling hills, a quaint farmhouse, and a winding dirt path leading to a distant forest."
p44 = "An opulent ballroom with golden chandeliers, elegantly dressed figures waltzing across a marble floor, and a string quartet playing softly in the corner."
p45 = "A remote cabin in the woods during a snowfall, with warm light spilling from its windows, smoke curling from the chimney, and footprints leading to the door."
p46 = "A vibrant coral reef teeming with life, colorful fish darting between the coral, and a gentle sea turtle gliding gracefully through the crystal-clear water."
p47 = "A post-apocalyptic wasteland where rusted vehicles litter the landscape, makeshift settlements emerge among ruins, and a lone survivor stands against a fiery sky."
p48 = "A magical academy perched atop a mountain, its spires reaching into the clouds, with students practicing spells in the courtyard below."
p49 = "A bustling harbor at sunset, with ships of all sizes anchored in the water, fishermen hauling in their catch, and seagulls circling overhead."
p50 = "An ancient library with towering bookshelves that reach the high, vaulted ceilings, filled with dusty leather-bound tomes and scrolls. Golden sunlight streams through arched stained-glass windows, casting vibrant patterns on the wooden floors. A spiral staircase with intricate wrought-iron railings connects the multiple levels, while a large central table is strewn with open books and an old globe. The air is thick with the scent of aged paper and ink, and a faint hum of whispers seems to echo through the vast space, hinting at the countless stories held within the walls. Cobwebs drape some forgotten corners, while glowing orbs of light hover gently, illuminating the space in a warm, magical glow."

p51 = "A futuristic robot battle arena enclosed in a transparent dome, offering a panoramic view of a sprawling cityscape with neon lights. Inside, sleek, humanoid robots face off, their metallic bodies reflecting the dazzling array of holographic effects swirling around them. Sparks fly as they exchange blows, each movement fluid and precise, with glowing energy weapons clashing in bursts of vivid color. The roaring crowd is a mix of humans and android spectators, their faces illuminated by the vibrant displays. Above, a floating scoreboard projects real-time statistics, and flying drones buzz around, capturing every angle of the intense fight. The atmosphere is electric, filled with cheers and the hum of futuristic machinery."

p52 = "A tranquil tropical island paradise surrounded by crystal-clear turquoise waters that gently lap against the soft, white sand. Tall palm trees sway in the gentle breeze, their shadows dancing on the ground. A hammock strung between two trees overlooks the ocean, while a colorful cocktail rests on a small table nearby. In the distance, a coral reef teeming with marine life can be seen through the water, and a lone sailboat drifts lazily under the warm sun. The air is filled with the sound of gentle waves, rustling leaves, and occasional chirps of tropical birds. The sky is painted in shades of orange and pink, signaling the approaching sunset and adding a magical glow to the scene."

p53 = "A grand gothic cathedral at twilight, its towering spires reaching into a sky painted in hues of orange and purple. The ornate façade is adorned with intricate carvings of angels and gargoyles, their shadows stretching across the cobblestone square below. Inside, the cavernous space is illuminated by the soft glow of flickering candles and the multicolored light streaming through massive stained-glass windows. Rows of wooden pews lead to a grand altar, where a golden cross stands beneath a high, vaulted ceiling adorned with elaborate frescoes. The air carries a sense of reverence and mystery, filled with the faint scent of incense and the distant echo of a choir singing hymns."

p54 = "An alien jungle teeming with life, filled with towering bioluminescent trees that glow in shades of blue, purple, and green. The forest floor is covered with unusual plants that pulse with light, while streams of mist swirl through the underbrush. Strange, otherworldly creatures with iridescent skin scurry and soar among the foliage, their calls blending into an otherworldly symphony. A glowing river winds through the landscape, its waters shimmering with particles of light. Above, a sky of swirling nebulae casts an ethereal glow over the scene, and the air hums with energy. An adventurous explorer in a sleek, high-tech suit carefully navigates this uncharted terrain, marveling at its beauty and mystery."

p55 = "A romantic Parisian street at night, bathed in the warm glow of vintage streetlamps. Cobblestone pathways lead past charming cafés with small round tables and wrought-iron chairs, where couples sit sipping wine and sharing quiet laughter. Flower boxes overflowing with colorful blooms adorn the windowsills, and the distant melody of an accordion player drifts through the cool evening air. The iconic Eiffel Tower rises majestically in the background, its lights twinkling like a thousand stars against the deep blue sky. The scent of fresh bread and pastries wafts from a nearby bakery, adding to the magic of the scene. A slight drizzle leaves the streets glistening, reflecting the lights and adding a touch of enchantment."

p56 = "A thrilling space battle unfolds against the vast backdrop of a star-filled galaxy. Sleek, futuristic starships maneuver through the darkness, their engines leaving trails of glowing blue light. Beams of energy and bursts of fiery explosions illuminate the void as opposing forces clash in a high-stakes confrontation. The camera perspective shifts between the chaos of the battle and a distant planet with swirling clouds and shimmering rings. Smaller fighter ships weave through the fray, engaging in dogfights with precision and daring. The command deck of the lead ship is a hive of activity, with holographic displays tracking every move. Amid the chaos, a lone pilot breaks formation, taking a daring course toward the enemy flagship."

p57 = "A hidden garden enclosed by tall, ancient stone walls covered in ivy and moss, creating an air of secrecy and tranquility. The centerpiece is a marble fountain adorned with intricate carvings, its water sparkling in the soft sunlight that filters through the canopy of blooming cherry trees. Vibrant flowers in every color imaginable line the pathways, their fragrance mingling with the fresh scent of earth. Butterflies and hummingbirds flit from blossom to blossom, adding to the serene ambiance. A wrought-iron bench sits beneath an archway covered in roses, inviting visitors to pause and soak in the beauty. The garden feels alive with a quiet magic, as if it holds centuries of untold stories."

p58 = "A mystical mountain monastery perched on a high peak, its stone walls blending seamlessly with the rocky terrain. Mist swirls around the structure, shrouding it in mystery, while prayer flags in vivid reds, yellows, and blues flutter in the crisp mountain breeze. Monks in saffron and maroon robes move silently along the winding pathways, some seated in meditation near intricately carved statues of deities. The sound of a gong resonates through the air, mixing with the distant roar of a waterfall cascading into a hidden valley below. Inside the monastery, the warm glow of oil lamps illuminates walls adorned with ancient murals and shelves filled with sacred texts, creating an atmosphere of profound peace and spirituality."

p59 = "A vibrant carnival parade snakes through the heart of a bustling city under the brilliance of a starry night. Extravagant floats adorned with bright lights and intricate designs roll past cheering crowds, each one a dazzling work of art. Performers in colorful, elaborate costumes dance and twirl to the rhythm of lively music played by a marching band. Confetti rains down from above, catching the glow of streetlamps and the neon lights of nearby buildings. Food vendors line the sidewalks, their stalls offering tantalizing treats like caramel apples, cotton candy, and roasted nuts. The energy of the celebration is electric, with laughter, music, and applause filling the air as the parade creates a feast for the senses."

p60 = "A snowy forest at twilight, its towering trees covered in a thick blanket of fresh white snow. A narrow path winds through the woods, the footprints of an unseen traveler the only sign of movement. The air is crisp and still, punctuated by the occasional creak of ice-laden branches. Soft, golden light glows from a lantern held by a figure in the distance, casting long shadows and illuminating their breath in the cold air. The faint sound of crunching snow underfoot echoes as they move deeper into the forest. Overhead, the first stars begin to twinkle in the darkening sky, while the peaceful beauty of the untouched winter landscape evokes a sense of wonder and calm."

p61 = "A futuristic underwater city enclosed in massive transparent domes, its sleek architecture glowing with soft blue and green lights. The city is a marvel of technology, with tall, streamlined buildings interconnected by glass tunnels where residents walk or travel in small pods. Outside the domes, schools of colorful fish and majestic sea creatures swim freely, their movements adding life to the aquatic environment. The seabed surrounding the city is dotted with glowing coral and underwater gardens, while above, faint rays of sunlight filter through the ocean's surface. The interior of the city buzzes with activity, with holographic displays, bustling markets, and areas dedicated to research and recreation. The harmony between technology and nature is strikingly beautiful."

p62 = "An ancient battlefield long since reclaimed by nature, its rolling hills now covered in green grass and wildflowers. Rusted swords, broken shields, and crumbling statues lie scattered among the landscape, serving as haunting reminders of the past. A faint mist clings to the ground, creating an eerie yet serene atmosphere. In the distance, a solitary figure stands silently, gazing at a toppled monument covered in moss. Birds chirp softly in the trees that have grown where armies once clashed, and the scent of earth and blooming flowers fills the air. The scene captures the passage of time, blending the echoes of history with the quiet beauty of nature’s reclamation, evoking a sense of reflection and melancholy."

p63 = "A cozy bakery at dawn, its large front window glowing with a warm golden light that spills onto the cobblestone street outside. Inside, shelves are filled with freshly baked bread, pastries, and cakes, their heavenly aroma wafting into the morning air. A baker wearing a flour-dusted apron stands behind the counter, arranging loaves of bread into neat rows. Customers sip steaming coffee at small wooden tables, chatting softly as the first rays of sunlight begin to peek over the horizon. The interior is rustic and inviting, with exposed brick walls, wooden beams, and a blackboard listing the day’s specials in elegant chalk handwriting. The bakery feels like a sanctuary, offering comfort and warmth to early risers."

p64 = "A fantastical floating island suspended in the sky, its edges adorned with waterfalls that cascade into the clouds below. At its center stands a majestic castle with tall, shimmering spires, surrounded by lush gardens filled with vibrant flowers and mythical creatures. Bridges made of glowing crystal connect smaller floating islands nearby, each one hosting unique features like ancient ruins, tranquil ponds, or orchards laden with golden fruit. The sky around the island is a canvas of swirling colors, painted with hues of pink, orange, and blue, while ethereal light beams from the island itself, suggesting powerful magic. The sound of cascading water and the gentle rustle of leaves creates an otherworldly symphony, making the scene feel like a dream."

p65 = "A lively pirate port bustling with activity under the warm light of a setting sun. Wooden docks stretch out into calm, turquoise waters, where ships of various sizes are moored, their sails fluttering in the breeze. Pirates in rugged clothing and tricorn hats unload crates of treasure, share boisterous laughter, and haggle with merchants at makeshift stalls. Taverns line the harbor, their doors wide open as music, laughter, and the scent of spiced rum drift into the salty air. Children chase each other along the docks, while seagulls circle above, cawing noisily. The horizon is dotted with more ships sailing into the port, their masts silhouetted against the golden glow of the setting sun. The scene is vibrant and full of life."

p66 = "A surreal dreamscape where the ground is composed of floating islands, each one connected by twisting, glowing bridges. The sky is a mesmerizing blend of swirling pastel colors, constantly shifting like a living canvas. Waterfalls cascade upwards into the clouds, defying gravity, while luminous orbs of light float serenely, casting soft glows on the landscape below. Strange, fantastical creatures roam the terrain, their forms both beautiful and otherworldly. A lone figure stands at the edge of one island, looking out over the expanse, their silhouette framed by a radiant rainbow that arcs across the entire horizon. The air feels alive with possibility, and every element of the scene suggests the limitless power of imagination."

p67 = "A peaceful riverside village nestled under a clear, starry night sky. Small cottages with thatched roofs line the banks of the gently flowing river, their windows glowing with warm, golden light. Lanterns hang from wooden posts, their flickering flames reflecting in the rippling water. A small wooden bridge arches gracefully over the river, connecting the two sides of the village. The sound of crickets and the occasional hoot of an owl fills the cool night air. Villagers gather around a bonfire in the central square, sharing stories and laughter, while others sit quietly by the river, watching the stars. The Milky Way stretches across the sky, casting a silvery glow over the idyllic scene, creating a sense of serene magic."

p68 = "A grand medieval banquet hall filled with the warm glow of chandeliers and the roaring fire from an enormous stone hearth. Long wooden tables are laden with golden goblets, roasted meats, fresh bread, and an abundance of fruits and cheeses. Nobles dressed in fine silks and velvet converse and laugh, their voices mingling with the lively music played by a group of minstrels in the corner. Servants bustle about, pouring wine into goblets and bringing in steaming dishes from the kitchen. The walls are adorned with banners bearing family crests, and the scent of spices and roasted food fills the air. A sense of festivity and camaraderie pervades the room, making it a celebration fit for kings and queens."

p69 = "A desolate lunar surface stretching out under the infinite blackness of space. The jagged, rocky terrain is illuminated by the faint light of a distant sun, casting long shadows. In the foreground, an astronaut in a white suit kneels, planting a flag that flutters faintly in the weak lunar wind. The Earth looms on the horizon, a vibrant blue and green orb glowing against the darkness. Nearby, the metallic structure of a small lunar lander reflects the pale light, its antenna reaching skyward. The silence is profound, broken only by the occasional crackle of the astronaut's radio. The scene captures a mix of isolation and wonder, emphasizing the fragile beauty of Earth seen from the stark emptiness of the moon."

p70 = "A magical winter wonderland blanketed in pristine snow, with tall pine trees shimmering under a clear, star-studded sky. A winding path leads through the forest, lit by glowing ice lanterns that cast soft, ethereal light. Children bundled in colorful scarves and hats laugh and sled down a sparkling hill, their joy echoing in the crisp, cold air. Nearby, a frozen lake reflects the brilliance of the northern lights, painting the scene with hues of green, purple, and pink. A quaint wooden cabin with smoke curling from its chimney stands at the edge of the clearing, offering warmth and comfort. The air is filled with the scent of pine and the faint jingle of sleigh bells, creating a sense of magic and peace."

p71 = "A post-apocalyptic cityscape where nature has begun to reclaim the crumbling remains of humanity. Skyscrapers stand partially collapsed, their facades covered in ivy and flowering vines. The streets are eerily quiet, with cars rusting where they were abandoned long ago. Small groups of survivors navigate the ruins, scavenging supplies, their voices hushed and wary. In the distance, a wild deer grazes near an overgrown playground, its presence a sign of nature's dominance over the forgotten urban world. The air is heavy with the scent of damp earth and rust, and the occasional call of birds echoes through the emptiness. Despite the desolation, the scene carries a quiet beauty, as life begins anew in the shadow of human achievement."

p72 = "A lush rainforest alive with vibrant energy, where towering trees stretch toward the sky, their dense canopies creating a world of dappled light below. The air is humid and filled with the calls of exotic birds, the hum of insects, and the distant roar of a cascading waterfall. Vines and brightly colored orchids drape from branches, while the forest floor is a carpet of moss, ferns, and fallen leaves. A troop of monkeys swings playfully between the branches, and a jaguar moves stealthily through the underbrush, its golden eyes gleaming. Streams of sunlight filter through gaps in the foliage, illuminating the shimmering wings of butterflies and the glistening water droplets on leaves, creating a scene teeming with life and wonder."

p73 = "A majestic waterfall plunges from a towering cliff into a crystal-clear pool surrounded by dense tropical greenery. The air is filled with the thunderous roar of water and the soft rustling of leaves in the breeze. Rays of sunlight pierce through the mist, creating a vivid rainbow arching over the scene. Ferns and brightly colored flowers frame the edges of the pool, their reflections shimmering in the still water. A group of small birds flits around the waterfall, their chirps blending with the symphony of nature. The pool’s surface is so clear that the smooth stones at the bottom are visible, adding to the serene beauty. The entire scene feels untouched and magical, a hidden gem of natural splendor."

p74 = "An elegant royal throne room, vast and adorned with intricate details that reflect its grandeur. The room is bathed in golden light from massive chandeliers hanging from a high, vaulted ceiling. Ornate pillars line the hall, each carved with symbols of the kingdom’s history. At the far end, a grand throne encrusted with jewels sits atop a dais, draped in rich velvet. A monarch dressed in resplendent robes sits regally, their crown gleaming under the light. Courtiers stand in attendance, murmuring softly, while knights in polished armor guard the entrance. The scent of incense fills the air, and the distant sound of a harp playing a soft melody adds to the atmosphere of power and majesty."

p75 = "An ancient jungle ruin hidden deep within a dense tropical forest, its stone structures weathered by time and covered in thick moss and vines. Carvings of forgotten deities and mysterious symbols adorn the walls, their details faded but still awe-inspiring. The air is humid and heavy with the scent of earth and blooming flowers. Shafts of sunlight pierce through the canopy, illuminating golden artifacts half-buried in the soil. The sound of rustling leaves and distant animal calls adds to the sense of mystery. A narrow stone pathway leads deeper into the ruins, where a faint, magical glow emanates from an inner chamber. The scene exudes an aura of secrecy and untold stories waiting to be discovered."

p76 = "A serene lakeside campsite nestled within a pine forest, the setting sun casting a warm orange glow across the still water. A small tent is pitched near the shore, and a campfire crackles softly, its smoke spiraling into the evening sky. The sound of gentle waves lapping against the rocks blends with the distant call of loons. A lone figure sits on a log, wrapped in a blanket, gazing at the reflection of the first stars appearing in the lake. Fireflies blink among the trees, adding to the enchanting atmosphere. Nearby, a fishing pole leans against a rock, suggesting a peaceful day spent at the water’s edge. The scene is tranquil and restorative, a perfect retreat from the world."

p77 = "A futuristic highway glowing with neon lights, slicing through a sprawling cyberpunk city under a stormy night sky. Sleek, high-tech vehicles zoom past at impossible speeds, their headlights reflecting on the rain-slicked road. Towering skyscrapers with holographic advertisements and neon signs dominate the horizon, their lights creating a kaleidoscope of colors. A lone figure in a trench coat and glowing visor stands at the edge of an overpass, surveying the chaos below. The air hums with the sound of engines, distant thunder, and the murmur of voices from the crowded streets. Above, drones zip between buildings, while lightning flashes intermittently, illuminating the intricate architecture. The scene is dynamic and intense, a snapshot of a vibrant, dystopian future."

p78 = "A fantastical underwater palace constructed from glowing coral, shimmering pearls, and translucent, bioluminescent structures. Towers spiraling toward the ocean surface are adorned with flowing kelp and schools of vibrant fish weaving through the openings. Inside, grand halls are illuminated by soft, radiant light emitted by glowing jellyfish and crystal chandeliers. Merfolk in elegant, flowing attire made from seaweed and shells move gracefully, their laughter blending with the soothing sounds of water. The floor is made of polished coral mosaics, depicting ancient sea myths. Outside, a massive reef teems with life, while rays of sunlight filter through the water, casting a mesmerizing play of light and shadows. The palace is a sanctuary of beauty and harmony beneath the waves."

p79 = "A dramatic volcanic landscape alive with fiery energy. Rivers of molten lava flow down jagged slopes, casting an orange-red glow that contrasts sharply with the blackened rock. Billowing plumes of smoke and ash rise into the darkened sky, where flashes of lightning occasionally illuminate the chaos. The ground trembles with the force of eruptions, and the air is thick with heat and the acrid scent of sulfur. In the foreground, a lone adventurer in protective gear stands at the edge of a cliff, silhouetted against the glowing magma. The scene is both awe-inspiring and foreboding, capturing the raw power of nature in its most destructive and beautiful form, a testament to the Earth's unrelenting energy."


# Hard
p80 = "An enchanted forest illuminated by bioluminescent plants, glowing in hues of neon blue and green. A misty river winds through the scene, reflecting the shimmering light like liquid glass. Giant mushrooms with glowing caps tower over the scene, their soft light casting shadows on the mossy ground. A mysterious figure, cloaked and hooded, stands on a small wooden bridge, holding a lantern that flickers like a firefly. Fireflies dart around in intricate patterns, creating an ethereal ambiance. The distant sound of waterfalls adds to the serene yet magical atmosphere, while a full moon casts a silver glow through the gaps in the dense canopy above."

p81 = "A futuristic cityscape at sunset, where towering skyscrapers made of glass and metal are intertwined with massive, glowing vines. The streets below are bustling with humanoid robots and humans in sleek, metallic suits, interacting harmoniously. Hovering vehicles zoom through the sky, leaving trails of iridescent light. A massive holographic billboard displays a stunning art installation of a swirling galaxy. The setting sun bathes the entire scene in a warm golden light, contrasting against the cool neon blue of the technology surrounding it. A child with augmented reality glasses marvels at a floating holographic butterfly, symbolizing the blend of nature and technology in this utopian future."

p82 = "A steampunk airship docked at a floating island high above the clouds. The airship is an intricate design of polished brass and leather, with massive propellers and glowing blue energy cores. The floating island is lush with green vegetation and dotted with Victorian-style buildings, their chimneys puffing out gentle wisps of smoke. Engineers and adventurers mill about, some examining mechanical gadgets while others carry crates of supplies. The sky is a canvas of soft pink and orange hues, with the sun setting on the horizon. A flock of birds glides past, their wings catching the golden light. The air buzzes with the sound of machinery and distant laughter."

p83 = "A serene beach at dawn, where the golden sand sparkles faintly as the first rays of sunlight stretch across the horizon. Gentle waves lap at the shore, their frothy edges catching the soft glow of the sunrise. A small wooden boat rests on the sand, filled with colorful fishing nets and a solitary lantern that still flickers faintly. In the background, a dense jungle rises, its leaves glistening with morning dew. A flock of flamingos wades through the shallow waters, their pink feathers vibrant against the tranquil backdrop. The salty breeze carries a faint melody, as if the ocean is singing a lullaby to the world."

p84 = "A dystopian wasteland, where a ruined cityscape is overrun by nature reclaiming its space. Crumbling skyscrapers are covered in vines, and trees grow through the shattered windows. A lone survivor stands atop a rusted vehicle, scanning the horizon with a pair of binoculars. The sky is an ominous gray, with thick clouds swirling overhead, threatening a storm. In the distance, a massive, glowing, mechanical obelisk rises, pulsing with an eerie green light. Wild animals roam freely through the desolate streets, their silhouettes casting long shadows. The air is thick with the smell of damp earth and decay, creating an atmosphere of melancholy and resilience."

p85 = "A mystical underwater kingdom, where coral structures tower like skyscrapers, glowing softly in various shades of pink, orange, and blue. Schools of brightly colored fish dart through the currents, while larger sea creatures glide gracefully in the distance. The scene is lit by a combination of bioluminescent flora and sunlight streaming through the surface above, creating dappled patterns of light and shadow. Merfolk with iridescent tails and intricate jewelry made of pearls and shells swim through the city, some tending to glowing gardens while others barter goods at an underwater market. The sound of distant whale songs adds to the magical serenity of the kingdom."

p86 = "A snowy mountain village during twilight, where cozy wooden cabins with smoking chimneys dot the landscape. The snow glistens under the soft purple and pink hues of the evening sky. A narrow cobblestone path winds through the village, illuminated by lanterns that cast a warm, golden glow. Villagers, bundled in fur-lined coats, gather around a central bonfire, where they share stories and hot drinks. In the background, the towering mountains rise majestically, their peaks kissed by the last light of the setting sun. A gentle snowfall adds a sense of peace to the enchanting winter scene."

p87 = "A grand medieval castle perched on a rocky cliff, overlooking a stormy sea. The castle's spires and towers reach towards the dark, thundercloud-filled sky, illuminated intermittently by flashes of lightning. The waves crash violently against the rocks below, sending sprays of mist into the air. A drawbridge leads to the castle gates, flanked by flickering torches that cast dancing shadows on the stone walls. In the courtyard, armored knights prepare for battle, their swords glinting in the dim light. Above, a solitary raven circles, its cry piercing through the sound of the raging storm."

p88 = "An ancient jungle temple partially submerged in a swamp, surrounded by massive, twisted trees with roots that snake into the murky water. The temple is covered in moss and vines, with intricate carvings of mythical creatures adorning its walls. The air is thick and humid, filled with the sound of chirping insects and the distant call of exotic birds. A lone explorer, clad in khaki and carrying a lantern, cautiously steps onto a crumbling stone platform. The water ripples below, hinting at the presence of something large and unseen. Shafts of sunlight break through the dense canopy, casting an ethereal glow on the forgotten structure."

p89 = "A bustling alien marketplace under a sprawling glass dome on a distant planet. The sky outside is a mesmerizing swirl of blue and purple nebulae, with twin suns casting a warm light. The market is filled with colorful stalls offering exotic goods, from glowing crystals to strange, floating fruits. Alien species of all shapes and sizes haggle and socialize, their languages forming a symphony of strange yet harmonious sounds. The air is filled with the aroma of spices and the hum of hovercrafts passing overhead. A musician plays a peculiar stringed instrument, adding a lively melody to the vibrant scene."

p90 = "A serene lakeside cabin at sunrise, surrounded by dense pine forests that stretch into the misty distance. The lake is a mirror, perfectly reflecting the soft oranges and pinks of the morning sky. A wooden pier extends into the water, where a lone figure sits, fishing pole in hand. The cabin has a stone chimney, from which a thin stream of smoke curls upwards, hinting at a warm fire inside. Birds chirp from the trees, and the gentle sound of water lapping against the shore creates a tranquil atmosphere. A deer grazes nearby, adding a touch of wilderness to the idyllic setting."

p91 = "A vibrant carnival at night, with colorful lights and banners illuminating the scene. A massive Ferris wheel towers in the background, its cabins glowing like lanterns. Crowds of people move through the fairground, laughing and enjoying the attractions. Food stalls offer cotton candy, popcorn, and glowing drinks, their scents wafting through the cool night air. Performers in bright costumes juggle flaming torches, while a magician dazzles an audience with a disappearing act. The air is filled with lively music, the distant sound of a carousel, and the occasional pop of fireworks bursting into the starry sky."

p92 = "A post-apocalyptic desert landscape, where the remains of a once-thriving city lie buried under sand dunes. Rusted vehicles and skeletal buildings peek out from the shifting sands. A caravan of survivors, clad in makeshift armor and goggles, trudges across the desert, led by a figure holding a banner that flutters in the hot wind. In the distance, a massive sandstorm looms, its swirling clouds lit by flashes of lightning. The air is dry and scorching, carrying the faint scent of dust and decay. A robotic scavenger scuttles across the sand, its glowing eyes scanning for salvageable materials."

p93 = "A tranquil Zen garden at sunset, where carefully raked sand patterns surround smooth stones and miniature bonsai trees. A wooden bridge arches over a koi pond, where fish swim lazily beneath the surface, their scales shimmering in the golden light. Cherry blossom petals drift through the air, adding a touch of pink to the serene scene. A monk in traditional robes sits cross-legged on a stone bench, meditating in silence. The distant sound of a bamboo water fountain fills the air, blending harmoniously with the soft rustling of leaves in the gentle breeze."

p94 = "A high-tech laboratory suspended in the sky, with walls of glass that offer a panoramic view of the clouds below. Scientists in futuristic attire work at holographic terminals, their movements precise and efficient. Robotic arms assemble intricate devices on sleek, metallic tables. The room is bathed in a cool blue light, accented by glowing data streams that float in the air. Outside, drones zip through the sky, delivering supplies to the facility. A young prodigy, wearing augmented reality glasses, stands at the center of the lab, presenting a groundbreaking invention to an audience of captivated researchers."

p95 = "A sprawling vineyard under a clear, starry night, where rows of grapevines stretch into the distance, their leaves glistening with dew. Lanterns hang from wooden posts, casting a soft, warm glow on the pathways. In the center of the vineyard, a rustic wooden table is set for a feast, adorned with candles, flowers, and bottles of wine. A group of friends sits around the table, laughing and toasting under the open sky. The scent of ripe grapes and fresh bread fills the air, mingling with the sound of gentle guitar music played by a performer nearby."

p96 = "A dramatic underwater scene of a shipwreck, with its once-majestic structure now home to vibrant marine life. Coral reefs have grown over the ship's hull, and schools of fish dart through the broken windows. Sunlight filters through the surface, creating a magical interplay of light and shadow. A scuba diver explores the wreck, their flashlight illuminating hidden treasures like a jeweled chest or ancient artifacts. In the background, a massive sea turtle glides gracefully past, while tiny bubbles rise from the diver's gear. The silence of the deep ocean is broken only by the muffled sound of the diver's breathing."

p97 = "A sprawling futuristic city at night, where towering skyscrapers are adorned with glowing holographic advertisements. Elevated trains glide along transparent tracks, their lights cutting through the darkness. Streets below are crowded with people and androids, illuminated by the neon signs of bustling shops and eateries. A cyberpunk aesthetic dominates, with individuals sporting augmented limbs and glowing tattoos. A vigilante in a sleek, black outfit watches over the city from a rooftop, their cape billowing in the wind. The distant hum of machinery and the occasional sound of a hovercar passing by create a dynamic, electric atmosphere."

p98 = "A fantastical scene of a dragon perched on a craggy mountaintop, its scales shimmering with iridescent hues that shift in the sunlight. The dragon's massive wings are partially unfurled, and its piercing eyes survey the valley below. The landscape is a mix of lush forests, cascading waterfalls, and a distant village with smoke rising from chimneys. A lone knight in gleaming armor stands at the base of the mountain, their sword drawn and shield raised, as if ready to face the mighty creature. The wind howls through the peaks, carrying the scent of pine and the faint crackle of magic in the air."

p99 = "A mystical portal in the middle of an ancient forest, glowing with swirling colors of purple, blue, and gold. The portal is surrounded by a circle of standing stones, each etched with glowing runes. The forest is alive with the sound of rustling leaves, chirping crickets, and distant howls. A hooded figure steps cautiously towards the portal, their staff glowing faintly in resonance with the energy emanating from the gateway. Fireflies dance around the scene, adding to the magical ambiance. The moonlight filters through the dense canopy above, casting intricate patterns on the mossy ground."

list_prompts = []

# Loop through and append prompts to the list
for i in range(100):  # Adjust range if you have fewer/more prompts
    list_prompts.append(globals()[f"p{i}"])